compile-base:build:
  stage: prep
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    IMG_TAG: compile
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$IMG_TAG" || true
    - docker build --squash --cache-from $CI_REGISTRY_IMAGE:$IMG_TAG -t $CI_REGISTRY_IMAGE:$IMG_TAG -f build-conf/compile/base.Dockerfile build-src
    - docker push "$CI_REGISTRY_IMAGE:$IMG_TAG"
  rules:
    - changes:
        - build-conf/compile/base.Dockerfile

depends:
  stage: depends
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    OSX_SDK: 10:11
  parallel:
    matrix:
      - BUILD: x86_64-unknown-linux-gnu
      - BUILD: i686-pc-linux-gnu
      - BUILD: arm-linux-gnueabihf
      - BUILD: aarch64-linux-gnu
      - BUILD: x86_64-w64-mingw32
      - BUILD: i686-w64-mingw32
      - BUILD: riscv64-linux-gnu
      - BUILD: x86_64-unknown-freebsd
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE:depends-$BUILD" || true
    - docker build --squash --build-arg BUILD=$BUILD --cache-from $CI_REGISTRY_IMAGE:depends-$BUILD -t $CI_REGISTRY_IMAGE:depends-$BUILD -f build-conf/compile/depends.Dockerfile build-src
    - docker push "$CI_REGISTRY_IMAGE:depends-$BUILD"
  rules:
    - changes:
        - build-conf/compile/depends.Dockerfile

depends:deploy:
  stage: deploy
  needs: ["depends"]
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  parallel:
    matrix:
      - TARGET: compile
      - TARGET: depends-x86_64-unknown-linux-gnu
      - TARGET: depends-x86_64-unknown-freebsd
      - TARGET: depends-i686-pc-linux-gnu
      - TARGET: depends-x86_64-w64-mingw32
      - TARGET: depends-i686-w64-mingw32
      - TARGET: depends-arm-linux-gnueabihf
      - TARGET: depends-aarch64-linux-gnu
      - TARGET: depends-riscv64-linux-gnu
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$TARGET || true
    - docker tag $CI_REGISTRY_IMAGE:$TARGET $DOCKER_REGISTRY/lthn/build:$TARGET
    - docker push $DOCKER_REGISTRY/lthn/build:$TARGET
  environment:
    name: $IMG_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
        - build-conf/compile/depends.Dockerfile

sources:
  stage: libs
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  parallel:
    matrix:
      - BUILD: osx
      - BUILD: linux
      - BUILD: win
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - sleep $(shuf -i1-180 -n1);
  script:
    - docker pull "$CI_REGISTRY_IMAGE:sources-$BUILD" || true
    - docker build --squash --build-arg BUILD=$BUILD -t $CI_REGISTRY_IMAGE:sources-$BUILD -f build-conf/compile/sources.Dockerfile build-src
    - docker push "$CI_REGISTRY_IMAGE:sources-$BUILD"
  rules:
    - changes:
        - build-conf/compile/sources.Dockerfile

sources:deploy:
  stage: deploy
  needs: ["sources"]
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  parallel:
    matrix:
      - TARGET: sources-osx
      - TARGET: sources-linux
      - TARGET: sources-win
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$TARGET || true
    - docker tag $CI_REGISTRY_IMAGE:$TARGET $DOCKER_REGISTRY/lthn/build:$TARGET
    - docker push $DOCKER_REGISTRY/lthn/build:$TARGET
  environment:
    name: $IMG_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
          - build-conf/compile/sources.Dockerfile