name: build:compile

on:
  push:
    branches: [ main ]
    paths:
      - build-conf/compile/sources.Dockerfile
      - build-conf/compile/base.Dockerfile
      - .github/workflows/compile.yml
  pull_request:
    paths:
      - build-conf/compile/sources.Dockerfile
      - build-conf/compile/base.Dockerfile
      - .github/workflows/compile.yml
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lthn/build:compile
          file: build-conf/compile/base.Dockerfile
  sources:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: source_macos
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: BUILD=osx
          tags: lthn/build:sources-osx
          file: build-conf/compile/sources.Dockerfile
      - name: Build and push
        id: source_linux
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: BUILD=linux
          tags: lthn/build:sources-linux
          file: build-conf/compile/sources.Dockerfile
      - name: Build and push
        id: source_windows
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: BUILD=win
          tags: lthn/build:sources-win
          file: build-conf/compile/sources.Dockerfile
