name: build:zano

on:
  push:
    branches: [ main ]
    paths:
      - build-conf/compile/zano.Dockerfile
      - .github/workflows/zano.yml
  pull_request:
    paths:
      - build-conf/compile/zano.Dockerfile
      - .github/workflows/zano.yml
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lthn/build:zano
          file: build-conf/compile/zano.Dockerfile

